import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Printer } from "lucide-react";

export default function PrintableComboForm() {
    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="bg-white min-h-screen p-8 max-w-4xl mx-auto">
            {/* Header - Hidden on small screens but visible for print */}
            <div className="flex justify-between items-center mb-8 border-b pb-4 print:border-none">
                <div className="flex items-center gap-4">
                    {/* Logo Placeholder */}
                    <div className="w-12 h-12 bg-purple-600 rounded-lg flex items-center justify-center text-white font-bold text-xl print:bg-black">
                        TE
                    </div>
                    <div>
                        <h1 className="text-2xl font-bold text-gray-900">TravEase Agency</h1>
                        <p className="text-sm text-gray-500">Travel Combo Request Form</p>
                    </div>
                </div>
                <Button onClick={handlePrint} className="print:hidden">
                    <Printer className="w-4 h-4 mr-2" /> Print Form
                </Button>
            </div>

            <div className="space-y-6 print:space-y-8">
                <p className="text-gray-600 italic border-l-4 border-gray-200 pl-4 print:text-sm">
                    Please fill out this form clearly. Once completed, scan or take a photo and upload it to the Operations Assistant.
                </p>

                {/* Form Grid */}
                <div className="grid grid-cols-1 gap-8 border border-gray-300 p-8 rounded-xl print:border-black print:p-4">

                    <div className="space-y-2">
                        <label className="block text-sm font-bold text-gray-900 uppercase tracking-wide">Package Title</label>
                        <div className="h-12 border-b-2 border-gray-300 border-dashed bg-gray-50 print:bg-transparent print:border-black"></div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        <div className="space-y-2">
                            <label className="block text-sm font-bold text-gray-900 uppercase tracking-wide">Base Price ($)</label>
                            <div className="h-12 border-b-2 border-gray-300 border-dashed bg-gray-50 print:bg-transparent print:border-black"></div>
                        </div>
                        <div className="space-y-2">
                            <label className="block text-sm font-bold text-gray-900 uppercase tracking-wide">Category</label>
                            <div className="h-12 border-b-2 border-gray-300 border-dashed bg-gray-50 print:bg-transparent print:border-black flex items-center gap-4 text-sm text-gray-400">
                                <span className="print:hidden">e.g. Luxury, Adventure, Family</span>
                            </div>
                        </div>
                    </div>

                    <div className="space-y-2">
                        <label className="block text-sm font-bold text-gray-900 uppercase tracking-wide">Description</label>
                        <div className="h-32 border-2 border-gray-300 border-dashed rounded-lg bg-gray-50 print:bg-transparent print:border-black"></div>
                    </div>

                    <div className="space-y-2">
                        <label className="block text-sm font-bold text-gray-900 uppercase tracking-wide">Inclusions (List items)</label>
                        <div className="h-24 border-2 border-gray-300 border-dashed rounded-lg bg-gray-50 print:bg-transparent print:border-black"></div>
                    </div>

                </div>

                {/* Footer */}
                <div className="pt-8 flex justify-between items-end">
                    <div className="text-xs text-gray-400 print:text-black">
                        Form ID: TE-OFFLINE-V1<br />
                        Generated by TravEase AI
                    </div>
                    <div className="text-center w-48">
                        <div className="h-0.5 bg-black mb-2"></div>
                        <p className="text-sm font-bold">Agent Signature</p>
                    </div>
                </div>
            </div>
        </div>
    );
}
